Cockpit 231
cockpit-project/cockpit-project.github.io pull request #353
Opened 2020-10-29 11:10 UTC by marusak

Preview: https://marusak.dev/cockpit-project.github.io/blog/cockpit-231.html

2020-10-29 19:35 UTC, marusak commented
Updated also URLs, this is ready for review.

2020-10-30 06:33 UTC, martinpitt requested changes
Dakujem!

2020-10-30 06:33 UTC, martinpitt commented on _posts/2020-10-29-cockpit-231.md
> +[USE](http://www.brendangregg.com/usemethod.html) method.
I don't think we need to be extra verbose about the old page, it just looks like this is being written twice. Also fixing some grammar issues.

```suggestion
The system graphs were replaced with a dedicated page for analyzing the current and historical performance of a machine. This page (reachable after clicking on 'View details and history' on the Overview page) shows current metrics as well as historical events based on the [USE](http://www.brendangregg.com/usemethod.html) method.
```

2020-10-30 06:33 UTC, martinpitt commented on _posts/2020-10-29-cockpit-231.md
> +Cockpit now includes the remote IP address when logging user logins (and login attempts). This means that the IP address will appear in the system logs, in the output of tools such as w or who, and i
We had this feature before, it was dropped with the introduction of cockpit-tls.

```suggestion
Cockpit records the remote IP address for user logins (and failed attempts) again. The IP address will appear in the system logs, in the output of tools such as `w` or `who`, and in the login-time messages about when the last successful login happened, and any failed login attempts. It also means that PAM modules can filter logins based on IP address (for example, temporarily blocking a subnet when there are too many failed login attempts).
```

2020-10-30 09:14 UTC, martinpitt approved these changes

2020-10-30 13:59 UTC, allisonkarlitskaya approved these changes

2020-10-31 07:57 UTC, merged