Remove Atomic Host as it is no longer supported upstream
cockpit-project/cockpit-project.github.io pull request #403
Opened 2021-04-15 16:03 UTC by travier

2021-04-15 16:23 UTC, cgwalters approved these changes

2021-04-15 16:56 UTC, martinpitt requested changes
Thanks for the cleanup!

2021-04-15 16:56 UTC, martinpitt commented on guide/latest/feature-sosreport.html
> +<p>If <code class="code">sosreport</code> is not found on a system, cockpit will attempt to run <code class="code">sosreport</code> in the <code class="code">rhel7/support-tools</code> docker contain
This bit needs to be dropped from this PR, as it gets auto-synced from cockpit: https://github.com/cockpit-project/cockpit/blob/master/doc/guide/feature-sosreport.xml I'm happy to do that myself tomorrow.

2021-04-15 17:42 UTC, dustymabe commented
Thanks @travier

2021-04-16 04:32 UTC, martinpitt commented
I took the liberty to force-push your branch with reverting the guide/ bits. Thanks!

2021-04-16 04:32 UTC, martinpitt approved these changes

2021-04-16 04:32 UTC, merged

2021-04-16 04:37 UTC, martinpitt commented
I sent https://github.com/cockpit-project/cockpit/pull/15702 to clean up the guide (and some related places).