script: Lowercase names when hypens exist
cockpit-project/cockpit-project.github.io pull request #436
Opened 2021-07-07 16:53 UTC by garrett

Before I forget, here's a possible fix for handling project names with lowercasing, to make @allisonkarlitskaya happier.

I haven't tested it yet, as it's late today and I just want to be done with Release-Notes for now, but I also don't want to forget this.

2021-07-08 06:27 UTC, allisonkarlitskaya requested changes

2021-07-08 06:27 UTC, allisonkarlitskaya commented on _scripts/generate-release-notes.rb
> +  repo.match('-') ? repo.downcase : repo.capitalize
i guess you could just use `repo`, since it's already lowercase?

2021-07-20 12:23 UTC, garrett commented
Resolved, rebased, and force pushed

2021-07-21 21:41 UTC, allisonkarlitskaya approved these changes

2021-07-22 04:30 UTC, merged