Cockpit 261
cockpit-project/cockpit-project.github.io pull request #484
Opened 2022-01-17 09:30 UTC by garrett

Preview: https://garrett.github.io/cockpit-project.github.io/blog/cockpit-261.html

2022-01-17 09:34 UTC, garrett commented
As usual, I generated the release notes with the following command:

```sh
_scripts/toolbox-ruby _scripts/generate-release-notes.rb -p
```

(There are other options available; run `-h` instead of `-p` to see them all. Most notable is that `-p` is for preview mode, which includes the pending PRs that haven't been merged and it includes links back to all the PRs with the release-note tag. There's also `-r` for when the projects have all been tagged for release, so versions in the release notes will match.)

Of course, this requires that the website toolbox is created first. If you haven't done that, run the following command before the command above:

```
_scripts/toolbox-create
```

2022-01-17 16:05 UTC, garrett commented
Reassigning. I probably can't take care of the release notes this week. But I think you two should have everything necessary.

One little gotcha: You'll want to `git reset --hard origin/main` before running the script, as:
- the document's filename is based on the date (so new days mean new filenames, until the day of the actual release)
- we wouldn't want old graphics lingering
- graphics are named based on the release and PR's title (so if the PR's title changes, the image filenames change too.)

2022-01-18 09:20 UTC, allisonkarlitskaya requested changes

2022-01-18 09:20 UTC, allisonkarlitskaya commented on _posts/2022-01-17-cockpit-261.md
> +This is accompanied by a general improvement in how destructive actions are summarized in the their dialogs.
```suggestion
This is accompanied by a general improvement in how destructive actions are summarized in their dialogs.
```

2022-01-18 09:20 UTC, allisonkarlitskaya commented on _posts/2022-01-17-cockpit-261.md
> +for pods and containers and add "Force restart" to the pod actions.
```suggestion
Add the pause and resume options — already available for pods — to
individual containers. Also make the order of the menu options the same
for pods and containers and add "Force restart" to the pod actions.
```

2022-01-18 09:20 UTC, allisonkarlitskaya commented on _posts/2022-01-17-cockpit-261.md
> +When a local image `fedora:latest` is available but a newer version is available on the image registry, checking the "pull latest image" checkbox will pull the latest version before creating the new
```suggestion
When the `:latest` tag of an image is available locally, but a newer version is available on the image registry, checking the "pull latest image" checkbox will now pull the latest version before creating the new container
```

2022-01-18 09:21 UTC, allisonkarlitskaya commented on _posts/2022-01-17-cockpit-261.md
> +*[CPU]: Central Processing Unit, the "brain" of a computer
also: lol.  seriously?  I don't think our target audience needs this if we're freely discussing pods, containers, image tags, unmounting busy filesystems, etc. all without further explanation.

2022-01-25 09:22 UTC, marusak commented
Thanks @allisonkarlitskaya for the review. I've updated the release notes themselves.

2022-01-25 09:33 UTC, garrett commented on _posts/2022-01-25-cockpit-261.md
> +## Add option to pull the latest image when creating a new container
```suggestion
## Podman: Add option to pull the latest image when creating a new container
```

This is lacking the "Podman" prefix.

2022-01-25 09:38 UTC, garrett commented
I've generated the release notes from the PRs. I guess it's time to polish up directly in the PR and we'll want to squash things down before/while merging.

First mod: Added Podman to one of the headings. 

We still need summary, links to be updated, etc.

2022-01-25 09:51 UTC, marusak commented
Added summary + links. Ready for review.

2022-01-25 11:11 UTC, martinpitt approved these changes
Thanks!

2022-01-25 13:48 UTC, merged