Cockpit 291
cockpit-project/cockpit-project.github.io pull request #629
Opened 2023-05-02 14:01 UTC by garrett

Preview: https://garrett.github.io/cockpit-project.github.io/blog/cockpit-291.html

2023-05-02 14:02 UTC, garrett commented
I haven't removed tags or edited anything yet.

2023-05-03 08:43 UTC, KKoukiou commented on _posts/2023-05-02-cockpit-291.md
> +{:.note}
Please link to blog post https://cockpit-project.org/blog/patternfly-v5-alpha.html

2023-05-05 11:59 UTC, martinpitt requested changes
Cheers!

2023-05-09 07:40 UTC, garrett commented on _posts/2023-05-03-cockpit-291.md
> +tags: cockpit, machines
```suggestion
tags: cockpit, machines, podman
```

2023-05-09 07:42 UTC, garrett commented on _posts/2023-05-03-cockpit-291.md
> +Users can now choose RAW as the storage format for the primary disk of their VM during the VM creation process.
"RAW" is not an acronym. It should be "raw". Also: We should not refer to people as "users". I'll reword this section.

2023-05-09 07:43 UTC, garrett commented on _posts/2023-05-03-cockpit-291.md
> +![Screenshot from 2023-05-03 12-40-15]({{ site.baseurl }}/images/291-redesign-vm-s-cpu-configuration-2.png)
People writing the descriptions need to have a blank line between images. I usually fix this myself.

2023-05-09 07:43 UTC, garrett commented on _posts/2023-05-03-cockpit-291.md
> +![Screenshot from 2023-05-03 12-40-15]({{ site.baseurl }}/images/291-redesign-vm-s-cpu-configuration-2.png)
```suggestion

![Screenshot from 2023-05-03 12-40-15]({{ site.baseurl }}/images/291-redesign-vm-s-cpu-configuration-2.png)
```

2023-05-09 07:45 UTC, garrett commented on _posts/2023-05-03-cockpit-291.md
> +summary: ''
```suggestion
summary: 'PatternFly 5, create VMs with raw disks, VM CPU editing refinements'
```

2023-05-09 12:58 UTC, martinpitt approved these changes
Yay, thanks! LGTM

2023-05-09 13:05 UTC, garrett commented
Oh, I still haven't edited the text yet.

2023-05-09 16:33 UTC, garrett reviewed
I've found the time to review (and change) the text. Apologies for the delay.

2023-05-09 16:33 UTC, garrett commented on _posts/2023-05-03-cockpit-291.md
> +The CPU model dialog and vCPU topology have been combined into a single field and a dialog. Additionally, a few minor improvements have been added, including vCPU maximum and vCPU count now being num
```suggestion
## Machines: Redesign virtual machine CPU configuration

The CPU model dialog and vCPU topology have been merged into a single overview entry and dialog. Additionally, a few minor improvements have been added, including vCPU maximum and vCPU count now being number inputs.
```

2023-05-09 16:33 UTC, garrett commented on _posts/2023-05-03-cockpit-291.md
> +Users can now choose RAW as the storage format for the primary disk during the VM creation process.
```suggestion
## Machines: VM creation supports raw disk format

During virtual machine creation, there is now a raw disk option in the storage format selection.
```

2023-05-09 16:33 UTC, garrett commented on _posts/2023-05-03-cockpit-291.md
> +Cockpit is now an "early adopter" of PatternFly 5. Everything should look the same. We ensured all functional and visual tests pass. While this should not affect people using Cockpit, it definitely w
```suggestion
## Update to PatternFly 5 alpha

Cockpit is now an "early adopter" of PatternFly 5. Everything should look the same. We ensured all functional and visual tests pass.

While this should not affect anyone using Cockpit, it definitely will affect everyone developing for Cockpit. Read more on [our PatternFly 5 blog post](https://cockpit-project.org/blog/patternfly-v5-alpha.html).
```

2023-05-10 10:50 UTC, merged