Add missing code snippets for PF5 alpha move
cockpit-project/cockpit-project.github.io pull request #630
Opened 2023-05-03 08:27 UTC by KKoukiou

2023-05-03 08:31 UTC, martinpitt requested changes
Can you please fix the broken "Upgrading to PatternFly 5" heading as well? It's also wrong to use bold text in a heading, let's leave the standard heading formatting.

2023-05-03 08:31 UTC, martinpitt commented on _posts/2023-05-03-patternfly-v5-alpha.md
> +<b>Cockpit has decided to go ahead with an early adoption of PatternFly 5.</b>The motivation for adopting PatternFly 5 can be summarized in several key points. Firstly, the early adoption of PatternF
Please don't use HTML markup in Markdown. `**` was correct, but it lacked a space after the second `**`.

2023-05-04 07:38 UTC, KKoukiou commented
Preview looks good now https://github.com/KKoukiou/cockpit-project.github.io/blob/main/_posts/2023-05-03-patternfly-v5-alpha.md

2023-05-04 08:17 UTC, martinpitt approved these changes
Cheers!

2023-05-04 08:17 UTC, merged