Cockpit 297
cockpit-project/cockpit-project.github.io pull request #649
Opened 2023-07-26 14:47 UTC by martinpitt

Preview: https://martinpitt.github.io/cockpit-project.github.io/blog/cockpit-297.html

2023-07-26 14:48 UTC, martinpitt commented on _posts/2023-07-26-cockpit-297.md
> +summary: 'Administrator can change user shell, Python bridge in fedora-39 and centos-stream-9, Show container's latest checkpoint'
```suggestion
summary: 'Administrator can change user shell, Python bridge in Fedora 38 and CentOS Stream/RHEL 9, show container's latest checkpoint'
```

2023-07-26 14:54 UTC, martinpitt commented on _posts/2023-07-26-cockpit-297.md
> +summary: 'Administrator can change user shell, Python bridge in fedora-39 and centos-stream-9, Show container's latest checkpoint'
Applied, and also fixed the quoting.

2023-07-27 13:37 UTC, garrett requested changes
How are these changes?

2023-07-27 13:37 UTC, garrett commented on _posts/2023-07-26-cockpit-297.md
> +## Allow administrators to change the user shell
```suggestion
## Support for changing user shells
```

2023-07-27 13:37 UTC, garrett commented on _posts/2023-07-26-cockpit-297.md
> +Administrators can now change a users shell via the user account page.
```suggestion
Administrators can now change user default shells on the Accounts page.
```

2023-07-27 13:37 UTC, garrett commented on _posts/2023-07-26-cockpit-297.md
> +## Move to Python bridge in Fedora 38 and CentOS Stream 9
```suggestion
## Use the Python bridge in Fedora 38 and CentOS Stream 9
```

2023-07-27 13:37 UTC, garrett commented on _posts/2023-07-26-cockpit-297.md
> +The rewritten Python bridge that was introduced in [Cockpit 294](https://cockpit-project.org/blog/cockpit-294.html) gets enabled on Fedora 38 and CentOS Stream 9. Please [let us know](https://github.
```suggestion
The rewritten Python bridge, introduced in [Cockpit 294](https://cockpit-project.org/blog/cockpit-294.html), is now used on Fedora 38 and CentOS Stream 9. Please [let us know](https://github.com/cockpit-project/cockpit/issues/new?template=bug_report.yml) if you run into any trouble!
```

2023-07-27 13:37 UTC, garrett commented on _posts/2023-07-26-cockpit-297.md
> +## Podman: Show time of container's latest checkpoint
```suggestion
## Podman: Show the time of the latest container checkpoint
```

2023-07-27 13:37 UTC, garrett commented on _posts/2023-07-26-cockpit-297.md
> +summary: "Administrator can change user shell, Python bridge in Fedora 38 and CentOS Stream/RHEL 9, Show container's latest checkpoint"
```suggestion
summary: "Support for changing user shell, Python bridge in Fedora 38 and CentOS Stream/RHEL 9, Show container's latest checkpoint"
```

2023-07-27 14:23 UTC, martinpitt commented on _posts/2023-07-26-cockpit-297.md
> +## Allow administrators to change the user shell
Please also prefix with "Users:"

2023-07-27 21:17 UTC, skobyda commented
All issues fixed

2023-07-27 21:18 UTC, skobyda approved these changes

2023-07-27 21:19 UTC, merged