Cockpit 307
cockpit-project/cockpit-project.github.io pull request #690
Opened 2023-12-14 08:39 UTC by jelly

2023-12-14 12:54 UTC, mvollmer requested changes

2023-12-14 12:54 UTC, mvollmer commented on _posts/2023-12-14-cockpit-307.md
> +## Machines: Change "Add disk" default behavior
This should be removed, it was already released with 303.

2023-12-14 12:54 UTC, mvollmer commented on _posts/2023-12-14-cockpit-307.md
> +![screenshot of ## storage redesign]({{ site.baseurl }}/images/307-storage-redesign.png)
This should be updated to 

![image](https://github.com/cockpit-project/cockpit-project.github.io/assets/3228183/ab1877c8-3c4e-415c-9cb1-06411db91570)

2023-12-15 12:07 UTC, martinpitt requested changes
Thanks!

2023-12-15 12:07 UTC, martinpitt commented on _posts/2023-12-14-cockpit-307.md
> +author: jelle
```suggestion
author: mvollmer
```

I think@mvollmer did most of the work here

2023-12-15 12:07 UTC, martinpitt commented on _posts/2023-12-14-cockpit-307.md
> +date: '2023-12-14'
```suggestion
date: '2023-12-15'
```

2023-12-15 12:07 UTC, martinpitt commented on _posts/2023-12-14-cockpit-307.md
> +summary: ''
```suggestion
summary: 'Storage redesign'
```

2023-12-15 12:07 UTC, martinpitt commented on _posts/2023-12-14-cockpit-307.md
> +The Storage page has been redesigned with the goal of making more things visible more of the time. The overview page now shows all storage objects in a table and allows almost all operations to be pe
"more of the time" sounds weird. Perhaps "in all views" or just drop it?

"to be" → "can be"

2023-12-18 08:38 UTC, martinpitt approved these changes
I pushed my proposed changes. Good enough for me now, thanks!

2023-12-18 09:23 UTC, allisonkarlitskaya requested changes

2023-12-18 09:23 UTC, allisonkarlitskaya commented on _posts/2023-12-14-cockpit-307.md
> +The Storage page has been redesigned with the goal of making more things visible in all views. The overview page now shows all storage objects in a table and allows almost all operations can be perfo
"allows almost all operations can be" doesn't work.

either

"almost all operations can be..."

or

"allows all operations to be..."

2023-12-18 09:23 UTC, allisonkarlitskaya commented on _posts/2023-12-14-cockpit-307.md
> +Clicking on a row navigates to a page dedicated to the object in that row, with more information and maybe a few more actions.
"maybe" sounds a bit informal.  Maybe "and in some cases, additional actions".

2023-12-18 09:23 UTC, allisonkarlitskaya commented on _posts/2023-12-14-cockpit-307.md
> +We will continue to improve the Storage pages, by adding filtering options to the big table and working on the actions and dialogs.
We called it "the storage page" above but here it's "the storage pages".

I might also try to reword the "We will continue" thing to something like "Future releases will continue this work by adding filtering..." etc.

2023-12-18 09:53 UTC, allisonkarlitskaya approved these changes
Thanks for the changes.

2023-12-18 09:59 UTC, martinpitt commented
Thanks you two for the updates, looks nice now! :+1:

2023-12-18 09:59 UTC, merged