Update applications.yml
cockpit-project/cockpit-project.github.io pull request #717
Opened 2024-03-22 16:54 UTC by MrGrymReaper

I recently found out an Cockpit application which is currently released and in active development, though not listed on the official website's applications list. Due to it being excluded from this list people are more likely to not know about this application, in order to fix this issue. I decided to contribute the necessary information to the project.

2024-03-24 08:37 UTC, martinpitt requested changes
Thanks!

2024-03-24 08:37 UTC, martinpitt commented on _data/applications.yml
> +     A Cockpit plugin to easily manage users and groups along with associated items.
Can you please make the description a bit more concrete? The builtin Accounts page can do all the [listed features](https://github.com/45drives/cockpit-identities?tab=readme-ov-file#features) except for setting the Samba password. I.e. please drop "easily", if possible avoid "manage", and replace the vague "associated items" with something more specific. I.e. it should answer the question "why and when would I want to install this?" Unfortunately the upstream project itself isn't very verbose in that regard.

2024-03-24 08:41 UTC, martinpitt commented on _data/applications.yml
> +     A Cockpit plugin to easily manage users and groups along with associated items.
To be more specific -- the 45drives apps are not very reliable. They have zero tests, do, well, "interesting" things with shell commands, don't fit the general Cockpit UI look and guidelines, etc. Presumably they did these for a specific product, but Cockpit is supported across a wide range of operating systems.

In other words, we don't want to recommend this page for standard Unix user management. If there's some "killer feature" which the Accounts page doesn't have, it should be pointed out as such.

2026-07-02 14:22 UTC, Venefilyn commented
Closing as the 45Drives Cockpit Identities is no longer being developed and has several outstanding issues

2026-07-02 14:22 UTC, closed without merging