posts: first Cockpit-files release
cockpit-project/cockpit-project.github.io pull request #737
Opened 2024-06-07 15:54 UTC by jelly

2024-06-07 15:55 UTC, jelly commented on _posts/2024-06-10-first-cockpit-files-release.md
> +We are working on getting Cockpit-files packaged in Fedora, Arch Linux and Debian. In the meantime this [copr repository](https://copr.fedorainfracloud.org/coprs/g/cockpit/main-builds/package/cockpit
@martinpitt taken the liberty to mention Debian but of course I won't be doing this, but will you? :)

2024-06-10 05:07 UTC, allisonkarlitskaya requested changes

2024-06-10 05:07 UTC, allisonkarlitskaya commented on _posts/2024-06-10-first-cockpit-files-release.md
> +![Cockpit Files list view](/images/cockpit-files-1-listview.png)
In general I think the screenshots are too large.  We might fake the contents of a "typical home directory" or other folder with 6-10 items in it which will show off all of the features (a folder or two, a wide range of file sizes, dates, file types) in a smaller amount of space.  An endless sea of folders with 'techy' names isn't too impressive looking.

Maybe also different folders/content for the icon vs list views to highlight the relative strengths of each?

2024-06-10 05:07 UTC, allisonkarlitskaya commented on _posts/2024-06-10-first-cockpit-files-release.md
> +We are working on getting Cockpit-files packaged in Fedora, Arch Linux and Debian. In the meantime this [copr repository](https://copr.fedorainfracloud.org/coprs/g/cockpit/main-builds/package/cockpit
Please either "Cockpit Files" or "cockpit-files".

2024-06-10 05:07 UTC, allisonkarlitskaya commented on _posts/2024-06-10-first-cockpit-files-release.md
> +We are working on getting Cockpit-files packaged in Fedora, Arch Linux and Debian. In the meantime this [copr repository](https://copr.fedorainfracloud.org/coprs/g/cockpit/main-builds/package/cockpit
oxford comma, and Debian, please.

2024-06-10 05:07 UTC, allisonkarlitskaya commented on _posts/2024-06-10-first-cockpit-files-release.md
> +We are working on getting Cockpit-files packaged in Fedora, Arch Linux and Debian. In the meantime this [copr repository](https://copr.fedorainfracloud.org/coprs/g/cockpit/main-builds/package/cockpit
comma splice: development snapshots, issues and feature requests

and maybe change "issues" to "bug reports"

2024-06-10 05:07 UTC, allisonkarlitskaya commented on _posts/2024-06-10-first-cockpit-files-release.md
> +title: First Cockpit-Files release
as above, "cockpit-files" or "Cockpit Files"

2024-06-10 05:07 UTC, allisonkarlitskaya commented on _posts/2024-06-10-first-cockpit-files-release.md
> +Last Friday we made the first release of cockpit-files, a new plugin for Cockpit to manage files on your server. Development on this new plugin was started by our GSoC student [Mahmoud Hamdy](https:/
Cockpit-styled with a hyphen.  But maybe mention Patternfly?  Is that a thing we do?  I notice that it's mentioned a lot when talking about the Anaconda webui...

2024-06-11 14:07 UTC, garrett commented
I've made some changes, which crop the screenshots and add a screenshot style (to get a border, as well as added the ability to make them align to the left) and shuffled some content around so it's not just a wall of text.

Shift-reload the preview URL to see the changes, otherwise the images might be an older cached version.

2024-06-11 15:07 UTC, allisonkarlitskaya requested changes
The "0 B" files in the screenshots look implausible.  Can you please give those reasonable file sizes for the respective file types?

2024-06-11 15:07 UTC, allisonkarlitskaya commented on _posts/2024-06-10-first-cockpit-files-release.md
> +Last Friday, we released the first version of Cockpit Files, a plugin for Cockpit to manage files on your server through your web browser. Cockpit Files was initially started by Google Summer of Code
Change the second , to a :.

2024-06-11 16:00 UTC, allisonkarlitskaya approved these changes
plz squash when merging

2024-06-11 16:00 UTC, merged

2024-06-12 07:26 UTC, garrett commented
> plz squash when merging

(There was an intentional separate commit that was unrelated to the other commit that was blog post... that was supposed to be separate. :frowning: )